[project]
name = "blast-julkalender"
version = "0.0.1"
dependencies = []
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
